<?php
// langues/ar.php

// Anciennes constantes
define('LIB_Connexion', 'تسجيل الدخول');
define('LIB_Accueil', 'الرئيسية');
define('LIB_GestionEtudiants', 'إدارة الطلاب');
define('LIB_GestionQCMs', 'إدارة QCMs');
define('LIB_PasserQCM', 'أداء QCM');
define('LIB_Quitter', 'تسجيل الخروج');
define('LIB_NomProjet', 'إدارة QCM');
define('LIB_Bienvenue', 'مرحبًا');
define('LIB_MessageBienvenue', 'مرحبًا بكم في منصتنا لإدارة QCMs!');
define('LIB_Login', 'اسم المستخدم');
define('LIB_MP', 'كلمة السر');
define('LIB_Nom', 'الاسم العائلي');
define('LIB_Prenom', 'الاسم الشخصي');
define('LIB_Matricule', 'رقم التسجيل');
define('LIB_Filiere', 'التخصص');
define('LIB_AnneeScolaire', 'السنة الأكاديمية');
define('LIB_Niveau', 'المستوى');
define('LIB_Sexe', 'الجنس');
define('LIB_Sexe_M', 'ذكر');
define('LIB_Sexe_F', 'أنثى');
define('LIB_Mail', 'البريد الإلكتروني');
define('LIB_SelectionnerFiliere', 'اختر التخصص');
define('LIB_SelectionnerAS', 'اختر السنة الأكاديمية');
define('LIB_SelectionnerNiveau', 'اختر المستوى');
define('LIB_Ajouter', 'أضف');
define('LIB_Lister', 'عرض');
define('LIB_Annuler', 'إلغاء');
define('LIB_Modifier', 'تعديل');
define('LIB_Etudiant', 'طالب');
define('LIB_Supprimer', 'حذف');
define('LIB_Actions', 'الإجراءات');
define('LIB_ConfirmationSuppression', 'هل أنت متأكد أنك تريد حذف هذا الطالب؟');
define('LIB_EnConstruction', 'الصفحة قيد الإنشاء...');
define('LIB_Photo', 'الصورة');
define('LIB_Password', 'كلمة المرور');
define('LIB_Details', 'التفاصيل');
define('LIB_DetailsEtudiant', 'تفاصيل الطالب');
define('LIB_CliquerPourUploader', 'انقر للتحميل');
define('LIB_MessageBienvenueLogin', 'يرجى تسجيل الدخول للوصول إلى مساحتك الشخصية وإدارة QCMs.');
define('LIB_ErorLogin', '!خطأ في تسجيل الدخول: يرجى التحقق من اسم المستخدم وكلمة المرور!');
define('LIB_QuestionsExistantes', 'الأسئلة الموجودة');
define('LIB_ConfirmSuppressionQuestion', 'هل أنت متأكد أنك تريد حذف هذا السؤال؟');
define('LIB_AucuneQuestion', 'لا توجد أسئلة لهذا QCM');
define('LIB_NotAuthorized', 'إجراء غير مصرح به');
define('LIB_InvalidID', 'معرّف غير صالح');
define('LIB_QuestionDeleted', 'تم حذف السؤال بنجاح');
define('LIB_DeleteError', 'حدث خطأ أثناء الحذف');
define('LIB_GeneralError', 'حدث خطأ ما');
define('LIB_QuestionAjoutee', 'تمت إضافة السؤال بنجاح');
define('LIB_QuestionModifiee', 'تم تعديل السؤال بنجاح');
define('LIB_QcmModifiee', 'تم تعديل QCM بنجاح');
define('LIB_Voir', 'عرض');
define('LIB_ConfirmationSuppressionQCM', 'هل أنت متأكد أنك تريد حذف هذا QCM؟');
define('LIB_TitreQCM', 'عنوان QCM');
define('LIB_ExempleNiveau', 'مثال: A1');
define('LIB_ListeQCMs', 'قائمة QCMs');
define('LIB_ID', 'المعرّف');
define('LIB_DateCreation', 'تاريخ الإنشاء');
define('LIB_AjouterQCM', 'إضافة QCM');
define('LIB_Question', 'السؤال');
define('LIB_Enonce', 'النص');
define('LIB_Commentaire', 'تعليق');
define('LIB_Reponses', 'الإجابات');
define('LIB_Reponse', 'الإجابة');
define('LIB_Enregistrer', 'حفظ');
define('LIB_ModifierQCM', 'تعديل QCM');
define('LIB_Titre', 'العنوان');
define('LIB_AjouterQuestion', 'إضافة سؤال جديد');
define('LIB_EnregistrerModifs', 'حفظ التعديلات');
define('LIB_QCM_ID_INVALIDE', 'معرف QCM غير صالح');
define('LIB_QCM_INTROUVABLE', 'QCM غير موجود');
define('LIB_Retour', 'عودة');
define('LIB_Dejapasse', 'تم إجراء QCM بالفعل');
define('LIB_Duree', 'المدة');
define('LIB_QCMDisponibles', 'الاختبارات المتاحة');
define('LIB_AucunQCM', 'لا توجد اختبارات متاحة');
define('LIB_QuestionsRepondues', 'الأسئلة المجابة');

define('LIB_BIENVENUE', 'مرحبًا');
define('LIB_MODE_ADMIN', 'وضع المسؤول');
define('LIB_STATS_ETUDIANTS', 'إحصائيات الطلاب');
define('LIB_TOTAL_ETUDIANTS', 'إجمالي الطلاب');
define('LIB_HOMMES', 'رجال');
define('LIB_FEMMES', 'نساء');
define('LIB_STATS_QCM', 'إحصائيات QCM');
define('LIB_QCM_CREES', 'الاختبارات التي تم إنشاؤها');
define('LIB_QUESTIONS', 'الأسئلة');
define('LIB_PASSAGES', 'المحاولات');
define('LIB_LISTE_QCM', 'قائمة الاختبارات');
define('LIB_NOTE_MOYENNE', 'المعدل');
define('LIB_DERNIERS_RESULTATS', 'آخر النتائج');
define('LIB_ETUDIANT', 'طالب');
define('LIB_NOTE', 'الدرجة');
define('LIB_DATE', 'التاريخ');
define('LIB_ETUDIANTS_PAR_FILIERE', 'الطلاب حسب التخصص');
define('LIB_ETUDIANTS_PAR_NIVEAU', 'الطلاب حسب المستوى');
define('LIB_MESSAGE_BIENVENUE', 'مرحبًا بكم في منصة إدارة الاختبارات!');
define('LIB_FILIERE', 'التخصص');
define('LIB_NIVEAU', 'المستوى');
define('LIB_QCM_DISPONIBLES', 'الاختبارات المتاحة');
define('LIB_QCM_COMPLETES', 'الاختبارات المكتملة');
define('LIB_VOIR_QCM', 'عرض الاختبارات');
define('LIB_MES_RESULTATS', 'نتائجي');
define('LIB_NOM_PROJET', 'إدارة الاختبارات');
define('LIB_TITRE', 'العنوان');
define('LANG_CODE', 'ar');
define('LIB_ACCUEIL', 'الرئيسية');
define('LIB_DUREE', 'المدة');

define('LIB_ResultatsQCM', 'نتائج الاختبار');
define('LIB_RetourGestionQCMs', 'العودة إلى إدارة الاختبارات');
define('LIB_InfosQCM', 'معلومات الاختبار');
define('LIB_Statistiques', 'الإحصائيات');
define('LIB_NombreEtudiants', 'عدد الطلاب');
define('LIB_NoteMoyenne', 'المعدل');
define('LIB_NoteMinMax', 'الحد الأدنى / الحد الأقصى');
define('LIB_DureeMoyenne', 'المدة المتوسطة');
define('LIB_ListeResultats', 'قائمة النتائج');
define('LIB_Numero', 'الرقم');
define('LIB_Email', 'البريد الإلكتروني');
define('LIB_Note', 'الدرجة');
define('LIB_DureeMin', 'المدة (ثانية)');
define('LIB_DatePassage', 'تاريخ الإجراء');
define('LIB_AucunResultatQCM', 'لا توجد نتائج لهذا الاختبار');

define('LIB_DetailsResultat', 'تفاصيل النتيجة');
define('LIB_Fermer', 'إغلاق');
define('LIB_ErreurChargementDetails', 'خطأ في تحميل التفاصيل.');
define('LIB_DetailsDuResultat', 'تفاصيل النتيجة');
define('LIB_ResultatIDInvalide', 'معرف النتيجة غير صالح.');
define('LIB_ResultatIntrouvable', 'النتيجة غير موجودة.');
define('LIB_ErreurRecupDetailsResultat', 'خطأ أثناء استرداد تفاصيل النتيجة');
?>
