<?php
// langues/en.php

// Anciennes constantes
define('LIB_Connexion', 'Login');
define('LIB_Accueil', 'Home');
define('LIB_GestionEtudiants', 'Student Management');
define('LIB_GestionQCMs', 'QCM Management');
define('LIB_PasserQCM', 'Take the QCM');
define('LIB_Quitter', 'Logout');
define('LIB_NomProjet', 'QCM Management');
define('LIB_Bienvenue', 'Welcome');
define('LIB_MessageBienvenue', 'Welcome to our QCM management platform!');
define('LIB_Login', 'Username');
define('LIB_MP', 'Password');
define('LIB_Nom', 'Last Name');
define('LIB_Prenom', 'First Name');
define('LIB_Matricule', 'Student ID');
define('LIB_Filiere', 'Department');
define('LIB_AnneeScolaire', 'Academic Year');
define('LIB_Niveau', 'Level');
define('LIB_Sexe', 'Gender');
define('LIB_Sexe_M', 'Male');
define('LIB_Sexe_F', 'Female');
define('LIB_Mail', 'Email');
define('LIB_SelectionnerFiliere', 'Select a department');
define('LIB_SelectionnerAS', 'Select an academic year');
define('LIB_SelectionnerNiveau', 'Select a level');
define('LIB_Ajouter', 'Add');
define('LIB_Lister', 'List');
define('LIB_Annuler', 'Cancel');
define('LIB_Modifier', 'Edit');
define('LIB_Etudiant', 'Student');
define('LIB_Supprimer', 'Delete');
define('LIB_Actions', 'Actions');
define('LIB_ConfirmationSuppression', 'Are you sure you want to delete this student?');
define('LIB_EnConstruction', 'Page under construction...');
define('LIB_Photo', 'Photo');
define('LIB_Password', 'Password');
define('LIB_Details', 'Details');
define('LIB_DetailsEtudiant', 'Student Details');
define('LIB_CliquerPourUploader', 'Click to upload');
define('LIB_MessageBienvenueLogin', 'Please log in to access your personal area and manage your QCMs.');
define('LIB_ErorLogin', 'Login error: please check your username and password!');
define('LIB_QuestionsExistantes', 'Existing Questions');
define('LIB_ConfirmSuppressionQuestion', 'Are you sure you want to delete this question?');
define('LIB_AucuneQuestion', 'No questions for this QCM');
define('LIB_NotAuthorized', 'Unauthorized action');
define('LIB_InvalidID', 'Invalid ID');
define('LIB_QuestionDeleted', 'Question deleted successfully');
define('LIB_DeleteError', 'Error during deletion');
define('LIB_GeneralError', 'An error occurred');
define('LIB_QuestionAjoutee', 'Question added successfully');
define('LIB_QuestionModifiee', 'Question modified successfully');
define('LIB_QcmModifiee', 'QCM modified successfully');
define('LIB_Voir', 'View');
define('LIB_ConfirmationSuppressionQCM', 'Are you sure you want to delete this QCM?');
define('LIB_TitreQCM', 'QCM Title');
define('LIB_ExempleNiveau', 'e.g., A1');
define('LIB_ListeQCMs', 'List of QCMs');
define('LIB_ID', 'ID');
define('LIB_DateCreation', 'Creation Date');
define('LIB_AjouterQCM', 'Add QCM');
define('LIB_Question', 'Question');
define('LIB_Enonce', 'Statement');
define('LIB_Commentaire', 'Comment');
define('LIB_Reponses', 'Answers');
define('LIB_Reponse', 'Answer');
define('LIB_Enregistrer', 'Save');
define('LIB_ModifierQCM', 'Edit QCM');
define('LIB_Titre', 'Title');
define('LIB_AjouterQuestion', 'Add a new question');
define('LIB_EnregistrerModifs', 'Save changes');
define('LIB_QCM_ID_INVALIDE', 'Invalid QCM ID');
define('LIB_QCM_INTROUVABLE', 'QCM not found');
define('LIB_Retour', 'Back');
define('LIB_Dejapasse', 'QCM already taken');
define('LIB_Duree', 'Duration');
define('LIB_QCMDisponibles', 'Available QCMs');
define('LIB_AucunQCM', 'No QCM available');
define('LIB_QuestionsRepondues', 'Answered questions');

define('LIB_BIENVENUE', 'Welcome');
define('LIB_MODE_ADMIN', 'Administrator Mode');
define('LIB_STATS_ETUDIANTS', 'Student Statistics');
define('LIB_TOTAL_ETUDIANTS', 'Total Students');
define('LIB_HOMMES', 'Men');
define('LIB_FEMMES', 'Women');
define('LIB_STATS_QCM', 'QCM Statistics');
define('LIB_QCM_CREES', 'QCM Created');
define('LIB_QUESTIONS', 'Questions');
define('LIB_PASSAGES', 'Attempts');
define('LIB_LISTE_QCM', 'List of QCMs');
define('LIB_NOTE_MOYENNE', 'Average Score');
define('LIB_DERNIERS_RESULTATS', 'Latest Results');
define('LIB_ETUDIANT', 'Student');
define('LIB_NOTE', 'Score');
define('LIB_DATE', 'Date');
define('LIB_ETUDIANTS_PAR_FILIERE', 'Students by Field');
define('LIB_ETUDIANTS_PAR_NIVEAU', 'Students by Level');
define('LIB_MESSAGE_BIENVENUE', 'Welcome to our QCM management platform!');
define('LIB_FILIERE', 'Field');
define('LIB_NIVEAU', 'Level');
define('LIB_QCM_DISPONIBLES', 'Available QCMs');
define('LIB_QCM_COMPLETES', 'Completed QCMs');
define('LIB_VOIR_QCM', 'View QCMs');
define('LIB_MES_RESULTATS', 'My Results');
define('LIB_NOM_PROJET', 'QCM Management');
define('LIB_TITRE', 'Titre');
define('LANG_CODE', 'fr');
define('LIB_ACCUEIL', 'Accueil');
define('LIB_DUREE', 'Durée');

define('LIB_ResultatsQCM', 'QCM Results');
define('LIB_RetourGestionQCMs', 'Back to QCM Management');
define('LIB_InfosQCM', 'QCM Information');
define('LIB_Statistiques', 'Statistics');
define('LIB_NombreEtudiants', 'Number of Students');
define('LIB_NoteMoyenne', 'Average Score');
define('LIB_NoteMinMax', 'Min / Max Score');
define('LIB_DureeMoyenne', 'Average Duration');
define('LIB_ListeResultats', 'Results List');
define('LIB_Numero', 'Number');
define('LIB_Email', 'Email');
define('LIB_Note', 'Score');
define('LIB_DureeMin', 'Duration (s)');
define('LIB_DatePassage', 'Date of Passage');
define('LIB_AucunResultatQCM', 'No results for this QCM');

define('LIB_DetailsResultat', 'Result Details');
define('LIB_Fermer', 'Close');
define('LIB_ErreurChargementDetails', 'Error loading details.');
define('LIB_DetailsDuResultat', 'Result Details');
define('LIB_ResultatIDInvalide', 'Invalid Result ID.');
define('LIB_ResultatIntrouvable', 'Result not found.');
define('LIB_ErreurRecupDetailsResultat', 'Error retrieving result details');
?>
