<?php
// langues/es.php

// Anciennes constantes
define('LIB_Connexion', 'Conexión');
define('LIB_Accueil', 'Inicio');
define('LIB_GestionEtudiants', 'Gestión de Estudiantes');
define('LIB_GestionQCMs', 'Gestión de QCMs');
define('LIB_PasserQCM', 'Realizar el QCM');
define('LIB_Quitter', 'Cerrar sesión');
define('LIB_NomProjet', 'Gestión de QCM');
define('LIB_Bienvenue', 'Bienvenido');
define('LIB_MessageBienvenue', '¡Bienvenido a nuestra plataforma de gestión de QCMs!');
define('LIB_Login', 'Usuario');
define('LIB_MP', 'Contraseña');
define('LIB_Nom', 'Apellido');
define('LIB_Prenom', 'Nombre');
define('LIB_Matricule', 'Matrícula');
define('LIB_Filiere', 'Carrera');
define('LIB_AnneeScolaire', 'Año Académico');
define('LIB_Niveau', 'Nivel');
define('LIB_Sexe', 'Género');
define('LIB_Sexe_M', 'Masculino');
define('LIB_Sexe_F', 'Femenino');
define('LIB_Mail', 'Correo electrónico');
define('LIB_SelectionnerFiliere', 'Seleccionar una carrera');
define('LIB_SelectionnerAS', 'Seleccionar un año académico');
define('LIB_SelectionnerNiveau', 'Seleccionar un nivel');
define('LIB_Ajouter', 'Agregar');
define('LIB_Lister', 'Listar');
define('LIB_Annuler', 'Cancelar');
define('LIB_Modifier', 'Editar');
define('LIB_Etudiant', 'Estudiante');
define('LIB_Supprimer', 'Eliminar');
define('LIB_Actions', 'Acciones');
define('LIB_ConfirmationSuppression', '¿Está seguro de que desea eliminar a este estudiante?');
define('LIB_EnConstruction', 'Página en construcción...');
define('LIB_Photo', 'Foto');
define('LIB_Password', 'Contraseña');
define('LIB_Details', 'Detalles');
define('LIB_DetailsEtudiant', 'Detalles del Estudiante');
define('LIB_CliquerPourUploader', 'Clic para subir');
define('LIB_MessageBienvenueLogin', 'Por favor, inicie sesión para acceder a su área personal y gestionar sus QCMs.');
define('LIB_ErorLogin', 'Error de conexión: ¡verifique su usuario y contraseña!');
define('LIB_QuestionsExistantes', 'Preguntas existentes');
define('LIB_ConfirmSuppressionQuestion', '¿Está seguro de que desea eliminar esta pregunta?');
define('LIB_AucuneQuestion', 'No hay preguntas para este QCM');
define('LIB_NotAuthorized', 'Acción no autorizada');
define('LIB_InvalidID', 'ID inválido');
define('LIB_QuestionDeleted', 'Pregunta eliminada con éxito');
define('LIB_DeleteError', 'Error al eliminar');
define('LIB_GeneralError', 'Ocurrió un error');
define('LIB_QuestionAjoutee', 'Pregunta agregada con éxito');
define('LIB_QuestionModifiee', 'Pregunta modificada con éxito');
define('LIB_QcmModifiee', 'QCM modificado con éxito');
define('LIB_Voir', 'Ver');
define('LIB_ConfirmationSuppressionQCM', '¿Está seguro de que desea eliminar este QCM?');
define('LIB_TitreQCM', 'Título del QCM');
define('LIB_ExempleNiveau', 'por ejemplo, A1');
define('LIB_ListeQCMs', 'Lista de QCMs');
define('LIB_ID', 'ID');
define('LIB_DateCreation', 'Fecha de creación');
define('LIB_AjouterQCM', 'Agregar QCM');
define('LIB_Question', 'Pregunta');
define('LIB_Enonce', 'Enunciado');
define('LIB_Commentaire', 'Comentario');
define('LIB_Reponses', 'Respuestas');
define('LIB_Reponse', 'Respuesta');
define('LIB_Enregistrer', 'Guardar');
define('LIB_ModifierQCM', 'Editar QCM');
define('LIB_Titre', 'Título');
define('LIB_AjouterQuestion', 'Agregar una nueva pregunta');
define('LIB_EnregistrerModifs', 'Guardar cambios');
define('LIB_QCM_ID_INVALIDE', 'ID de QCM inválido');
define('LIB_QCM_INTROUVABLE', 'QCM no encontrado');
define('LIB_Retour', 'Regresar');
define('LIB_Dejapasse', 'QCM ya realizado');
define('LIB_Duree', 'Duración');
define('LIB_QCMDisponibles', 'QCM disponibles');
define('LIB_AucunQCM', 'No hay QCM disponible');
define('LIB_QuestionsRepondues', 'Preguntas respondidas');

define('LIB_BIENVENUE', 'Bienvenido');
define('LIB_MODE_ADMIN', 'Modo Administrador');
define('LIB_STATS_ETUDIANTS', 'Estadísticas de Estudiantes');
define('LIB_TOTAL_ETUDIANTS', 'Total de Estudiantes');
define('LIB_HOMMES', 'Hombres');
define('LIB_FEMMES', 'Mujeres');
define('LIB_STATS_QCM', 'Estadísticas de QCM');
define('LIB_QCM_CREES', 'QCM creados');
define('LIB_QUESTIONS', 'Preguntas');
define('LIB_PASSAGES', 'Intentos');
define('LIB_LISTE_QCM', 'Lista de QCM');
define('LIB_NOTE_MOYENNE', 'Nota Promedio');
define('LIB_DERNIERS_RESULTATS', 'Últimos Resultados');
define('LIB_ETUDIANT', 'Estudiante');
define('LIB_NOTE', 'Nota');
define('LIB_DATE', 'Fecha');
define('LIB_ETUDIANTS_PAR_FILIERE', 'Estudiantes por Especialidad');
define('LIB_ETUDIANTS_PAR_NIVEAU', 'Estudiantes por Nivel');
define('LIB_MESSAGE_BIENVENUE', '¡Bienvenido a nuestra plataforma de gestión de QCM!');
define('LIB_FILIERE', 'Especialidad');
define('LIB_NIVEAU', 'Nivel');
define('LIB_QCM_DISPONIBLES', 'QCM disponibles');
define('LIB_QCM_COMPLETES', 'QCM completados');
define('LIB_VOIR_QCM', 'Ver QCM');
define('LIB_MES_RESULTATS', 'Mis Resultados');
define('LIB_NOM_PROJET', 'Gestión de QCM');
define('LIB_TITRE', 'Título');
define('LANG_CODE', 'es');
define('LIB_ACCUEIL', 'Inicio');
define('LIB_DUREE', 'Duración');

define('LIB_ResultatsQCM', 'Resultados del QCM');
define('LIB_RetourGestionQCMs', 'Volver a la gestión de QCM');
define('LIB_InfosQCM', 'Información del QCM');
define('LIB_Statistiques', 'Estadísticas');
define('LIB_NombreEtudiants', 'Número de estudiantes');
define('LIB_NoteMoyenne', 'Nota promedio');
define('LIB_NoteMinMax', 'Nota mínima / máxima');
define('LIB_DureeMoyenne', 'Duración promedio');
define('LIB_ListeResultats', 'Lista de resultados');
define('LIB_Numero', 'Número');
define('LIB_Email', 'Correo electrónico');
define('LIB_Note', 'Nota');
define('LIB_DureeMin', 'Duración (s)');
define('LIB_DatePassage', 'Fecha de realización');
define('LIB_AucunResultatQCM', 'No hay resultados para este QCM');

define('LIB_DetailsResultat', 'Detalles del Resultado');
define('LIB_Fermer', 'Cerrar');
define('LIB_ErreurChargementDetails', 'Error al cargar los detalles.');
define('LIB_DetailsDuResultat', 'Detalles del Resultado');
define('LIB_ResultatIDInvalide', 'ID de resultado inválido.');
define('LIB_ResultatIntrouvable', 'Resultado no encontrado.');
define('LIB_ErreurRecupDetailsResultat', 'Error al recuperar los detalles del resultado');
?>
