<?php
// langues/fr.php

// Anciennes constantes
define('LIB_Connexion', 'Connexion');
define('LIB_Accueil', 'Accueil');
define('LIB_GestionEtudiants', 'Gestion des Étudiants');
define('LIB_GestionQCMs', 'Gestion des QCMs');
define('LIB_PasserQCM', 'Passer le QCM');
define('LIB_Quitter', 'Déconnexion');
define('LIB_NomProjet', 'Gestion QCM');
define('LIB_Bienvenue', 'Bienvenue');
define('LIB_MessageBienvenue', 'Bienvenue sur notre plateforme de gestion de QCM !');
define('LIB_Login', 'Login');
define('LIB_MP', 'Mot de passe');
define('LIB_Nom', 'Nom');
define('LIB_Prenom', 'Prénom');
define('LIB_Matricule', 'Matricule');
define('LIB_Filiere', 'Filière');
define('LIB_AnneeScolaire', 'Année Académique');
define('LIB_Niveau', 'Niveau');
define('LIB_Sexe', 'Sexe');
define('LIB_Sexe_M', 'Homme');
define('LIB_Sexe_F', 'Femme');
define('LIB_Mail', 'Email');
define('LIB_SelectionnerFiliere', 'Sélectionner une filière');
define('LIB_SelectionnerAS', 'Sélectionner une année scolaire');
define('LIB_SelectionnerNiveau', 'Sélectionner un niveau');
define('LIB_Ajouter', 'Ajouter');
define('LIB_Lister', 'Lister');
define('LIB_Annuler', 'Annuler');
define('LIB_Modifier', 'Modifier');
define('LIB_Etudiant', 'Étudiant');
define('LIB_Supprimer', 'Supprimer');
define('LIB_Actions', 'Actions');
define('LIB_ConfirmationSuppression', 'Êtes-vous sûr de vouloir supprimer cet étudiant ?');
define('LIB_EnConstruction', 'Page en construction...');
define('LIB_Photo', 'Photo');
define('LIB_Password', 'Mot de passe');
define('LIB_Details', 'Détails');
define('LIB_DetailsEtudiant', 'Détails de l\'étudiant');
define('LIB_CliquerPourUploader', 'Cliquer pour uploader');
define('LIB_MessageBienvenueLogin', 'Connectez-vous pour accéder à votre espace personnel et gérer vos QCM.');
define('LIB_ErorLogin', 'Erreur de connexion: veuillez vérifier votre identifiant et mot de passe!');
define('LIB_QuestionsExistantes', 'Questions existantes');
define('LIB_ConfirmSuppressionQuestion', 'Êtes-vous sûr de vouloir supprimer cette question ?');
define('LIB_AucuneQuestion', 'Aucune question pour ce QCM');
define('LIB_NotAuthorized', 'Action non autorisée');
define('LIB_InvalidID', 'Identifiant invalide');
define('LIB_QuestionDeleted', 'Question supprimée avec succès');
define('LIB_DeleteError', 'Erreur lors de la suppression');
define('LIB_GeneralError', 'Une erreur est survenue');
define('LIB_QuestionAjoutee', 'Question ajoutée avec succès');
define('LIB_QuestionModifiee', 'Question modifiée avec succès');
define('LIB_QcmModifiee', 'QCM modifiée avec succès');
define('LIB_Voir', 'Voir');
define('LIB_ConfirmationSuppressionQCM', 'Êtes-vous sûr de vouloir supprimer ce QCM ?');
define('LIB_TitreQCM', 'Titre du QCM');
define('LIB_ExempleNiveau', 'Par exemple : A1');
define('LIB_ListeQCMs', 'Liste des QCMs');
define('LIB_ID', 'ID');
define('LIB_DateCreation', 'Date de création');
define('LIB_AjouterQCM', 'Ajouter un QCM');
define('LIB_Question', 'Question');
define('LIB_Enonce', 'Énoncé');
define('LIB_Commentaire', 'Commentaire');
define('LIB_Reponses', 'Réponses');
define('LIB_Reponse', 'Réponse');
define('LIB_Enregistrer', 'Enregistrer');
define('LIB_ModifierQCM', 'Modifier le QCM');
define('LIB_Titre', 'Titre');
define('LIB_AjouterQuestion', 'Ajouter une nouvelle question');
define('LIB_EnregistrerModifs', 'Enregistrer les modifications');
define('LIB_QCM_ID_INVALIDE', 'ID de QCM invalide');
define('LIB_QCM_INTROUVABLE', 'QCM introuvable');
define('LIB_Retour','Retour');
define('LIB_Dejapasse', 'QCM déjà passé');
define('LIB_Duree', 'Durée');
define('LIB_QCMDisponibles', 'QCM disponibles');
define('LIB_AucunQCM', 'Aucun QCM disponible');
define('LIB_QuestionsRepondues', 'Questions répondues');

define('LIB_BIENVENUE', 'Bienvenue');
define('LIB_MODE_ADMIN', 'Mode Administrateur');
define('LIB_STATS_ETUDIANTS', 'Statistiques des Étudiants');
define('LIB_TOTAL_ETUDIANTS', 'Total des Étudiants');
define('LIB_HOMMES', 'Hommes');
define('LIB_FEMMES', 'Femmes');
define('LIB_STATS_QCM', 'Statistiques des QCM');
define('LIB_QCM_CREES', 'QCM créés');
define('LIB_QUESTIONS', 'Questions');
define('LIB_PASSAGES', 'Passages');
define('LIB_LISTE_QCM', 'Liste des QCM');
define('LIB_NOTE_MOYENNE', 'Note Moyenne');
define('LIB_DERNIERS_RESULTATS', 'Derniers Résultats');
define('LIB_ETUDIANT', 'Étudiant');
define('LIB_NOTE', 'Note');
define('LIB_DATE', 'Date');
define('LIB_ETUDIANTS_PAR_FILIERE', 'Étudiants par Filière');
define('LIB_ETUDIANTS_PAR_NIVEAU', 'Étudiants par Niveau');
define('LIB_MESSAGE_BIENVENUE', 'Bienvenue sur notre plateforme de gestion de QCM !');
define('LIB_FILIERE', 'Filière');
define('LIB_NIVEAU', 'Niveau');
define('LIB_QCM_DISPONIBLES', 'QCM disponibles');
define('LIB_QCM_COMPLETES', 'QCM complétés');
define('LIB_VOIR_QCM', 'Voir les QCM');
define('LIB_MES_RESULTATS', 'Mes Résultats');
define('LIB_NOM_PROJET', 'Gestion QCM');
define('LIB_TITRE', 'Titre');
define('LANG_CODE', 'fr');
define('LIB_ACCUEIL', 'Accueil');
define('LIB_DUREE', 'Durée');

define('LIB_ResultatsQCM', 'Résultats du QCM');
define('LIB_RetourGestionQCMs', 'Retour à la gestion des QCMs');
define('LIB_InfosQCM', 'Informations sur le QCM');
define('LIB_Statistiques', 'Statistiques');
define('LIB_NombreEtudiants', 'Nombre d\'étudiants');
define('LIB_NoteMoyenne', 'Note moyenne');
define('LIB_NoteMinMax', 'Note min / max');
define('LIB_DureeMoyenne', 'Durée moyenne');
define('LIB_ListeResultats', 'Liste des résultats');
define('LIB_Numero', 'Numéro');
define('LIB_Email', 'Email');
define('LIB_Note', 'Note');
define('LIB_DureeMin', 'Durée (s)');
define('LIB_DatePassage', 'Date de passage');
define('LIB_AucunResultatQCM', 'Aucun résultat pour ce QCM');

define('LIB_DetailsResultat', 'Détails du Résultat');
define('LIB_Fermer', 'Fermer');
define('LIB_ErreurChargementDetails', 'Erreur lors du chargement des détails.');
define('LIB_DetailsDuResultat', 'Détails du Résultat');
define('LIB_ResultatIDInvalide', 'ID de Résultat invalide.');
define('LIB_ResultatIntrouvable', 'Résultat introuvable.'); 
define('LIB_ErreurRecupDetailsResultat', 'Erreur lors de la récupération des détails du résultat');
?>